### ISSUE TITLE
Using module causes Better Rolls for NPCs to revert to public after first roll.

### ISSUE THREAD

**Issue by Miaradz** [crash1115/blind-roll-skills#17]
![2021-01-25 12_33_47-Foundry Virtual Tabletop • A Standalone Virtual Tabletop Application](https://user-images.githubusercontent.com/66564401/105663837-34814500-5f0e-11eb-9e19-fd17ce4d2142.png)

**Comment by crash1115** [comment]
Whoops! Thanks for the report, patching now. Should have a release out soon.

**Comment by crash1115** [comment]
Patched in 0.5.2
