### ISSUE TITLE
[Feature] Adding support for hidden death saving throws

### ISSUE THREAD

**Issue by hoyer1066** [crash1115/blind-roll-skills#19]

**Comment by crash1115** [comment]
Hi there, thanks for the suggestion!

This is probably something I can implement, but it'll come with a caveat: I can hide the rolls, both in chat and on 3d dice, but hiding the results on the character sheet to make them truly blind is out of scope for this project. 

This means that a player could roll the save blindly and nobody would be able to see it, but anyone with access would still be able to look at their sheet and see total successes/failure and be able to figure out the result of the roll from that. This mirrors the behavior presently in core, as if you'd had the player select Blind GM Roll during the roll dialog.

Is that okay?

**Comment by hoyer1066** [comment]
I think that would be perfect (maybe even private GM roll rather than blind?)
Basically this comes from how I've always played death saves in-person - which is a hidden roll between the down PC and the DM, keeping the death save results and totals hidden from the rest of the players to increase tension and minimise meta-gaming around the death saves etc.

"Your friend is down, get your ass moving coz you have no idea when they'll be out for good"

**Comment by crash1115** [comment]
Doing a Private GM roll would require a bit more of an overhaul than I think I'm willing to do right now, but blind is definitely doable. I've got the code written for this already, just needs some testing. Looking at a release sometime this weekend.

Thank you for taking the time to give feedback! Really appreciate it. :smile:
