### ISSUE TITLE
Include Attack Rolls

### ISSUE THREAD

**Issue by flamewave000** [crash1115/blind-roll-skills#27]
My players and I also do blind attack rolls. This way they don't know what the AC is and it helps keep everyone from Meta-Gaming where maybe adding that extra 1d4 to your roll "might" be enough, but you're not sure and you have to go by my description of the situation to make the decision. I also use Health Estimate which shows the visible state of the creature.

It would be great if you could include Attacks as an option in this module.

**Comment by crash1115** [comment]
I was actually going to look into this for the next release; I'm pretty sure it should be doable. 👍

**Comment by crash1115** [comment]
Update on this: I've built out the functionality that works with core dnd5e rolls in 0.8.0, but it's going to require buy-in from the authors of the roll-altering modules out there (midi, BR, etc) to get it working with those. That said, the feature hasn't been "launched" yet. Gonna wait until I can get some time to work with Tim and Supe and whoever else to get it implemented so it all goes smoothly on release.
