### ISSUE TITLE
Doesn't work in 0.8.6

### ISSUE THREAD

**Issue by plumppig** [crash1115/blind-roll-skills#28]
There are no error messages thrown, but none of the configured ability checks are being hidden. The repo is flagged for 0.7.9 so I understand that's likely expected, but is there intention to update?

(I've tried turning off every module except this one)

**Comment by crash1115** [comment]
What version of the module are you running? Latest (0.7.1) should work fine in Foundry 0.8.x.

**Comment by plumppig** [comment]
Oh interesting, The Forge appears to say 0.7.0 is the latest (see below).  Lemme see if I can't manually grab the 0.7.1 version and install it.

![Screen Shot 2021-07-08 at 10 36 04 AM](https://user-images.githubusercontent.com/5460707/124959348-58c27100-dfd8-11eb-9e82-f6fa182fe737.png)

**Comment by plumppig** [comment]
Ahh, looks like the JSON file has it flagged as a minimum version of 0.8.7 is required; so I suspect The Forge is detecting that and limiting my ability to install it.  

If it's 0.8.x compatible should the minimumCoreVersion and compatibleCoreVersion attributes be modified to reflect that?

**Comment by crash1115** [comment]
Sorry, I misspoke (that's what I get for responding to bug reports at 2am). 

The min version 0.8.7 is correct; Foundry had an issue up until 0.8.7 that prevented private rolls from displaying correctly and made the module unusable in 0.8.0 through 0.8.6. There's not really much of anything I can do about that, so compatibility with 0.8.6 isn't an option, unfortunately.

**Comment by plumppig** [comment]
Totally get it :) Thank you!
