### ISSUE TITLE
Does Not Work with Midi-qol enabled

### ISSUE THREAD

**Issue by Avitale34** [crash1115/blind-roll-skills#29]
For some reason this no longer works for me.

**Comment by crash1115** [comment]
You using midi, by any chance?

**Comment by Avitale34** [comment]
Yes I am

**Comment by crash1115** [comment]
A recent update to midi changed something that interferes with how Auto Blind Rolls detects if a roll should be blind. Midi isn't a module I support unfortunately, so it's not something that'll be fixed.

I _am_ looking into seeing what I can do down the line to allow these roll-altering modules to add support for auto blind rolls themselves, in a non-painful way. If/when I get that working, I'll be able to put in a request for midi to take care of that. I don't have a timeline for that tho.

**Comment by dmaneyapanda** [comment]
Thanks for the update.  Just adding in a vote for continuing to look for a solution, since I also use both midi and this module, and am sorely missing this module's functionality now.

**Comment by dmaneyapanda** [comment]
I also added a tracking issue at midiqol: https://gitlab.com/tposney/midi-qol/-/issues/444

**Comment by crash1115** [comment]
I just dropped the update that should allow module authors to implement their own support for Auto Blind Rolls. If Tim decides it's something he wants to pursue, the tools now exist, but it's really up to him.

I dropped a link to the documentation in the issue on his gitlab so he can check it out.

**Comment by crash1115** [comment]
Should be resolved as of version 0.8.34 of midi.
