### ISSUE TITLE
Compatibility with Ready Set Rolls Modules. v10

### ISSUE THREAD

**Issue by Dom-Odyssey** [crash1115/blind-roll-skills#36]
Ready Set Roll is the v10 version of better rolls 5e, it seems that skills are not rolling blind automatically if ready set roll is use on skills.

https://github.com/MangoFVTT/fvtt-ready-set-roll-5e

**Comment by ohmusama** [comment]
can confirm this is also the case with Ready Set Roll

**Comment by crash1115** [comment]
Blind Rolls should be functional with v10 now. I left a feature request over on the RSR repository for Mango to take a look at (https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/issues/133); if/when he can get to that, things should work as expected.

**Comment by crash1115** [comment]
Should all be working now with v1.4.0 of RSR and v0.9.0 of Auto Blind Rolls. Tested on Foundry build 291 and dnd5e v2.1.2.

**Comment by ohmusama** [comment]
Awesome, thank you!
