### ISSUE TITLE
ReferenceError: oldDsn is not defined (combined with The Furnace)

### ISSUE THREAD

**Issue by mvanduijvenvoorde** [crash1115/blind-roll-skills#8]
I think the following error in my console happens with your module active, combined with The Furnace module.

foundry.js:2242 ReferenceError: oldDsn is not defined
    at blindrolls.js:73
    at Function._call (foundry.js:2239)
    at Function.call [as __furnace_original_call] (foundry.js:2224)
    at Function.callOriginalFunction (Patches.js:57)
    at Function.<anonymous> (Debug.js:42)
    at Function.create (foundry.js:9743)
    at Function.create (foundry.js:28276)
    at Item5e.showItemCard (itemhandling.js:205)
    at async Item5e.doItemRoll (itemhandling.js:136)

**Comment by mvanduijvenvoorde** [comment]
- Foundry 0.6.6
- Furnace 2.2
- dnd5e 0.98
- Hide Skill Rolls 0.4.2

**Other Modules active:**
- Sky's Alternate sheet 1.3.4
- Better NPC sheet 0.8.3
- Lib - Color Settings 2.5.1
- Conditions for 5e 0.4.5.7
- Custom Hotbar 2.0.5
- Dice Tray 0.6.0
- Dice So Nice 2.0.4
- Dynamic Effects 0.5.101
- Easy Target 2.3
- Max Crit 0.1.6
- Midi QOL 0.3.6
- Permission Viewer 0.7
- Show Artwork 1.0.0
- Token Action HUD 0.7.17
- Turn Alert 1.5.1

It happens when I click a weapon to roll for hit to attack a Skeleton: (for example: game.dnd5e.rollItemMacro("Scimitar");)
It triggers 2 errors when I do that.

**Comment by mvanduijvenvoorde** [comment]
It has to do with a different module

I only activated the following modules as a test:
- Sky alternate sheet
- Better NPC sheet
- Crash Hide Skill Rolls
- Custom Hotbar
- Dynamic Effects
- Furnace
- Max Crit

No errors now...

**Comment by mvanduijvenvoorde** [comment]
I found the culprit, its the module: Dice So Nice.

**Comment by crash1115** [comment]
That makes more sense, thanks! Managed to track down the error, should have a fix out shortly.

**Comment by crash1115** [comment]
Fixed in v0.4.3
